android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
unityStreamingAssets=
unityTemplateVersion=25
unityProjectPath=C:/Users/bhave/Desktop/NEW-Outfit-Studio-/Unity3DModule
unity.projectPath=C:/Users/bhave/Desktop/NEW-Outfit-Studio-/Unity3DModule
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=26
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.DefaultCompany.Unity3DModule
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=1.0
unity.namespace=com.DefaultCompany.Unity3DModule
unity.agpVersion=9.0.0
unity.javaCompatibilityVersion=VERSION_17
unity.javaCompatabilityVersion=VERSION_17
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.installInBuildFolder=false
